/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
    theme: {
        extend: {
            colors: {
                "background": "#f9f9f9",
                "on-error": "#ffffff",
                "secondary": "#8a4e40",
                "on-tertiary-container": "#ffffff",
                "secondary-fixed-dim": "#e39988",
                "on-primary": "#e2e2e2",
                "outline-variant": "#c6c6c6",
                "on-secondary": "#ffffff",
                "on-primary-fixed-variant": "#e2e2e2",
                "on-tertiary": "#d4e3ff",
                "on-secondary-container": "#370e05",
                "on-primary-fixed": "#ffffff",
                "surface-container-lowest": "#ffffff",
                "outline": "#777777",
                "on-background": "#1a1c1c",
                "inverse-primary": "#c6c6c6",
                "on-error-container": "#410002",
                "inverse-surface": "#2f3131",
                "tertiary-fixed": "#0060ac",
                "inverse-on-surface": "#f1f1f1",
                "surface-container": "#eeeeee",
                "on-tertiary-fixed": "#ffffff",
                "secondary-fixed": "#ffb4a3",
                "on-primary-container": "#ffffff",
                "surface-container-highest": "#e2e2e2",
                "primary-container": "#3b3b3b",
                "error-container": "#ffdad6",
                "primary-fixed-dim": "#474747",
                "on-surface-variant": "#474747",
                "primary": "#000000",
                "surface-container-low": "#f3f3f3",
                "surface-dim": "#dadada",
                "on-surface": "#1a1c1c",
                "surface-variant": "#e2e2e2",
                "on-secondary-fixed": "#370e05",
                "secondary-container": "#ffc8bb",
                "surface-tint": "#5e5e5e",
                "surface-bright": "#f9f9f9",
                "tertiary-container": "#2976c7",
                "error": "#ba1a1a",
                "tertiary-fixed-dim": "#004883",
                "on-secondary-fixed-variant": "#602d20",
                "primary-fixed": "#5e5e5e",
                "tertiary": "#003c70",
                "on-tertiary-fixed-variant": "#d4e3ff",
                "surface-container-high": "#e8e8e8",
                "surface": "#f9f9f9"
            },
            fontFamily: {
                "headline": ["Inter"],
                "body": ["Inter"],
                "label": ["Inter"]
            },
            borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
        },
    },
};